# Generated by Codex assistant
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_birth', models.DateField()),
                ('employee_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('is_admin', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_employee',
                'ordering': ['employee_name'],
            },
        ),
        migrations.CreateModel(
            name='CheckInHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('in', 'Check In'), ('out', 'Check Out')], max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='checkin.employee')),
            ],
            options={
                'db_table': 'tbl_checkin_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
