# Generated by Django 5.2.7 on 2025-11-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinhistory',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
